---
version: 2

# https://goreleaser.com/customization/project/
project_name: obsolete-packages

# https://goreleaser.com/customization/build/
builds:
  - id: "{{ .ProjectName }}"
    binary: ".build/{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}" # https://goreleaser.com/customization/templates/
    flags:
      - -trimpath
      - -buildvcs=false
    tags:
      - static_build
    ldflags:
      - -s -w -extldflags -static
      - -X main.version=v{{ .Version }}
      - -X main.gitCommit={{ .ShortCommit }}
      - -X main.makeBin=/usr/bin/make
    goos:
      - freebsd
    goarch:
      - amd64
      - arm64

# https://goreleaser.com/customization/archive/
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: ["zip"]
    strip_binary_directory: true
    files: []

# https://goreleaser.com/customization/changelog/
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch

# https://goreleaser.com/customization/checksum/
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}.sha256"
  # algorithm: sha256 # default

# https://goreleaser.com/customization/sign/#with-cosign
signs:
  - cmd: cosign
    artifacts: checksum
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - "sign-blob"
      - "--yes"
      - "${artifact}"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"

# https://goreleaser.com/customization/release/
release:
  # draft: true # If set to true, will not auto-publish the release
  use_existing_draft: true
  replace_existing_artifacts: true
  mode: replace
  extra_files:
    - glob: "dist/{{ .ProjectName }}_{{ .Version }}.sha256"
    - glob: "dist/{{ .ProjectName }}_{{ .Version }}.sha256.sig"
    - glob: "dist/{{ .ProjectName }}_{{ .Version }}.sha256.pem"
